#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.chiang.GestureLock.Resource", IsApplication=false)]

namespace com.chiang.GestureLock
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int color_finger_on = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int color_finger_up = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int color_no_finger_inner_circle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int color_no_finger_outer_circle = 2130771969;
			
			// aapt resource value: 0x7f010004
			public static int count = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int tryTimes = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GestureLockThumbnail = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public static int GestureLockThumbnail_count = 0;
			
			public static int[] GestureLockViewGroup = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public static int GestureLockViewGroup_color_finger_on = 2;
			
			// aapt resource value: 3
			public static int GestureLockViewGroup_color_finger_up = 3;
			
			// aapt resource value: 0
			public static int GestureLockViewGroup_color_no_finger_inner_circle = 0;
			
			// aapt resource value: 1
			public static int GestureLockViewGroup_color_no_finger_outer_circle = 1;
			
			// aapt resource value: 4
			public static int GestureLockViewGroup_count = 4;
			
			// aapt resource value: 5
			public static int GestureLockViewGroup_tryTimes = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
