#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.chiang.TestApp.Resource", IsApplication=true)]

namespace com.chiang.TestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.chiang.GestureLock.Resource.Attribute.color_finger_on = global::com.chiang.TestApp.Resource.Attribute.color_finger_on;
			global::com.chiang.GestureLock.Resource.Attribute.color_finger_up = global::com.chiang.TestApp.Resource.Attribute.color_finger_up;
			global::com.chiang.GestureLock.Resource.Attribute.color_no_finger_inner_circle = global::com.chiang.TestApp.Resource.Attribute.color_no_finger_inner_circle;
			global::com.chiang.GestureLock.Resource.Attribute.color_no_finger_outer_circle = global::com.chiang.TestApp.Resource.Attribute.color_no_finger_outer_circle;
			global::com.chiang.GestureLock.Resource.Attribute.count = global::com.chiang.TestApp.Resource.Attribute.count;
			global::com.chiang.GestureLock.Resource.Attribute.tryTimes = global::com.chiang.TestApp.Resource.Attribute.tryTimes;
			global::com.chiang.GestureLock.Resource.String.ApplicationName = global::com.chiang.TestApp.Resource.String.ApplicationName;
			global::com.chiang.GestureLock.Resource.String.Hello = global::com.chiang.TestApp.Resource.String.Hello;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockThumbnail = global::com.chiang.TestApp.Resource.Styleable.GestureLockThumbnail;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockThumbnail_count = global::com.chiang.TestApp.Resource.Styleable.GestureLockThumbnail_count;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockViewGroup = global::com.chiang.TestApp.Resource.Styleable.GestureLockViewGroup;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockViewGroup_color_finger_on = global::com.chiang.TestApp.Resource.Styleable.GestureLockViewGroup_color_finger_on;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockViewGroup_color_finger_up = global::com.chiang.TestApp.Resource.Styleable.GestureLockViewGroup_color_finger_up;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockViewGroup_color_no_finger_inner_circle = global::com.chiang.TestApp.Resource.Styleable.GestureLockViewGroup_color_no_finger_inner_circle;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockViewGroup_color_no_finger_outer_circle = global::com.chiang.TestApp.Resource.Styleable.GestureLockViewGroup_color_no_finger_outer_circle;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockViewGroup_count = global::com.chiang.TestApp.Resource.Styleable.GestureLockViewGroup_count;
			global::com.chiang.GestureLock.Resource.Styleable.GestureLockViewGroup_tryTimes = global::com.chiang.TestApp.Resource.Styleable.GestureLockViewGroup_tryTimes;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int color_finger_on = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int color_finger_up = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int color_no_finger_inner_circle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int color_no_finger_outer_circle = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int count = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int tryTimes = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int bgcolor = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int forcecolor = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int gray = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int menubgcolor = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int transparent_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int id_gestureLockThumbnail = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int id_gestureLockViewGroup = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int txtTitle = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GestureLockThumbnail = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int GestureLockThumbnail_count = 0;
			
			public static int[] GestureLockViewGroup = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int GestureLockViewGroup_color_finger_on = 2;
			
			// aapt resource value: 3
			public const int GestureLockViewGroup_color_finger_up = 3;
			
			// aapt resource value: 0
			public const int GestureLockViewGroup_color_no_finger_inner_circle = 0;
			
			// aapt resource value: 1
			public const int GestureLockViewGroup_color_no_finger_outer_circle = 1;
			
			// aapt resource value: 4
			public const int GestureLockViewGroup_count = 4;
			
			// aapt resource value: 5
			public const int GestureLockViewGroup_tryTimes = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
